name: Deploy
description: execute 'make deploy' command
inputs:
  path:
    description: Path to Service
    required: true

runs:
  using: "composite"
  steps:
    - name: âš™ï¸ Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0

    - name: â¬‡ï¸ Install gotestsum
      shell: bash
      run: |
        go install gotest.tools/gotestsum@v1.12.0

    - name: âš™ï¸ Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: â¬‡ï¸ Install AWS CDK
      run: npm install -g aws-cdk
      shell: bash

    - name: ğŸš€ Execute Deploy
      run: make deploy --directory ${{ inputs.path }}
      shell: bash
